1.Write a Python Program to Add Two Matrices?

In [43]:
import numpy as np
def addMatrices(a,b):
    if len(a[0]) == len(b):
        result = np.matrix(a) + np.matrix(b)
        print(f'Add to matrices is {result}')
    else:
        print('Matrix Addition not possible')
    
addMatrices([[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]])

Add to matrices is [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


2.Write a Python Program to Multiply Two Matrices?

In [42]:
import numpy as np
def multiplyMatrices(a,b):
    if len(a[0]) == len(b):
        result = np.matrix(a) * np.matrix(b)
        print(f'Add to matrices is {result}')
    else:
        print('Matrix multiplication not possible')
    
addMatrices([[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]])

Add to matrices is [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


3.Write a Python Program to Transpose a Matrix?

In [49]:
import numpy as np
def transpose(a):
        result = np.matrix(a).T
        print(f'Add to matrices is : {result}')
    
transpose([[1,2,3],[4,5,6],[7,8,9]])

Add to matrices is : [[1 4 7]
 [2 5 8]
 [3 6 9]]


4.Write a Python Program to Sort Words in Alphabetic Order?

In [62]:
def alphabeticOrder():
    string = input('Enter string: ').lower()
    print(f'Alphabetic order of string is {sorted(string)}')
    
alphabeticOrder()

Enter string: Hardik
Alphabetic order of string is ['a', 'd', 'h', 'i', 'k', 'r']


5.Write a Python Program to Remove Punctuation From a String?

In [72]:
import re
def removePunctustion(test_str):  
    test_str = input('Enter the string : ')
    res = re.sub(r'[^\w\s]','',test_str)
    print(f'The String after removing punctustion is : {res}')
    

removePunctustion(test_str)
    

Enter the string : "Gfg is best:&^&*%%&*%^&$ for!%%#$%$#^&% Geeks ~~!~@!~!@;"
The String after removing punctustion is : Gfg is best for Geeks 
